### ISSUE TITLE
error when used together with hiccup 

### ISSUE THREAD

**Issue by roti** [weavejester/ring-serve#3]
Hi,

I have following setup:
:dependencies [[org.clojure/clojure "1.2.1"]
                 [org.clojure/clojure-contrib "1.2.0"]
                 [compojure "1.0.1"]
                 [hiccup "1.0.0-beta1"]]
  :dev-dependencies [[ring-serve "0.1.2"]]

When evaluating following form:

(ns myapp.core
    (:use compojure.core, ring.util.serve)
    (:require [compojure.route :as route]))

i get following error:

defelem does not exist
  [Thrown class java.lang.IllegalAccessError]

roti

**Comment by weavejester** [comment]
Hiccup 1.0 is not compatible with Ring 1.0. You'll need to use a previous version of Hiccup, or a later version of Ring.
