### ISSUE TITLE
'ring.util.serve misses the class org.mortbay.log.Logger

### ISSUE THREAD

**Issue by vrescobar** [weavejester/ring-serve#8]
I am calling it from the repl, no matter what I do I always get the error.
Environment:
Leiningen 2.5.0 on Java 1.8.0_05 Java HotSpot(TM) 64-Bit Server VM (MacOSX)
Found on: [ring-serve "0.1.2"]

The easiest method to is to follow the example code:

project.handler=> (defn handler [request]
        {:status 200
         :headers {"Content-Type" "text/plain"}
         :body "Hello World"})
(defn handler [request]
           #_=>         {:status 200
           #_=>          :headers {"Content-Type" "text/plain"}
           #_=>          :body "Hello World"})
# 'project.handler/handler

project.handler=> (use 'ring.util.serve)
(use 'ring.util.serve)

CompilerException java.lang.ClassNotFoundException: org.mortbay.log.Logger, compiling:(ring/util/serve.clj:1:1) 
project.handler=>

**Comment by weavejester** [comment]
Ring-Serve is rather out of date and should probably be considered deprecated. I'll add a notice to the README.

A modern solution for REPL-based servers is to use [Ring-Server](https://github.com/weavejester/ring-server) or a component-based system like [Duct](https://github.com/weavejester/duct).

**Comment by vrescobar** [comment]
Oh such a pity... Is there any alternative suggested for REPL serving/live
debugging?

Some clojure packagers suggest alternatives when that happen.

Thank you for the fast answer.
Am 20.01.2015 14:36 schrieb "James Reeves" notifications@github.com:

**Comment by vrescobar** [comment]
Now I saw the recommendation links from your original comment. Thank you again.
